[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["data/**", "public/images/**", "server.js"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
